config/routes.rb
Rails.application.routes.draw do

  resources :patients do
    resources :prescriptions do
      resources :pa_requests do
        resource :request_pages
      end
    end
  end

  resources :pa_requests, :only => [:index]
  resource :request_pages, :only => [:show, :create]

  root 'home#index'

  get '/dashboard' => 'pa_requests#index'

  get '/help' => 'home#help'

  get '/api' => redirect("https://api.covermymeds.com/#overview"), :as => :api_documentation

end

app/models/pa_request.rb
class PaRequest < ActiveRecord::Base
  belongs_to :prescription
end

app/controllers/pa_requests_controller.rb
class PaRequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = PaRequest.all
  end

  # GET /patients/1/prescriptions/1/pa_requests/1
  # GET /patients/1/prescriptions/1/pa_requests/1.json
  def show
    if @pa_request.cmm_link
      respond_to do |format|
        format.html { redirect_to @pa_request.cmm_link+"?token_id=#{@pa_request.cmm_token}" }
        format.json { render :show, status: :ok, location: @pa_request}
      end
    end
  end

  # GET /patients/1/prescriptions/1/pa_requests/new
  def new
    @patient = Patient.find(params[:patient_id])
    @prescription = @patient.prescriptions.find(params[:prescription_id])
    @request = @prescription.pa_requests.build
  end

  # GET /patients/1/prescriptions/1/pa_requests/1/edit
  def edit
    @patient      = Patient.find params[:patient_id]
    @prescription = @patient.prescriptions.find params[:prescription_id]
    @request   = @prescription.pa_requests.find params[:id]
  end

  # POST /patients/1/prescriptions/1/pa_requests
  # POST /patients/1/prescriptions/1/pa_requests.json
  def create
    @patient = Patient.find(params[:patient_id])
    @prescription = @patient.prescriptions.find(params[:prescription_id])
    @pa_request = @prescription.pa_requests.build(pa_request_params)

    respond_to do |format|
      if @pa_request.save
        format.html { redirect_to @patient, notice: 'PaRequest was successfully started.' }
        format.json { render :show, status: :created, location: @prescription }
      else
        format.html { render :new }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @patient = Patient.find(params[:patient_id])
      @prescription = @patient.prescriptions.find(params[:prescription_id])
      @pa_request = @prescription.pa_requests.find(params[:id])
      logger.debug "#{@pa_request}"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pa_request_params
      params.require(:pa_request).permit(:prescription_id, :form_id, :urgent, :state, :sent, :cmm_token, :cmm_link, :cmm_id, :cmm_workflow_status)
    end

  end

app/helpers/pa_requests_helper.rb
module PaRequestsHelper

  def cmm_request_link_for(request)
    params = {
      :api_id => '1vd9o4427lyi0ccb2uem',
      :token_id => request.cmm_token,
      :id => request.id
    }
    if request.cmm_link
      request.cmm_link+"?token_id=#{params[:token_id]}"
    else
      "https://api.covermymeds.com/requests/#{request.cmm_id}?v=1&#{params.to_query}"
    end
  end
end

app/views/pa_requests/_form.html.erb
<h1>New PA Request</h1>
<%= form_for [@patient, @prescription, @request] do |f| %>

<% if @request.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@request.errors.count, "error") %> prohibited this prescription from being saved:</h2>

  <ul>
    <% @request.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div id="request-add" class="template">
  <fieldset>
    <legend><h2>Patient Details</h2>  <%= link_to "Edit Patient", edit_patient_path(@patient), :class=>'btn btn-info' %> </legend>    

    <div class='form-group'>
      <%= f.label :patient, "Name" %>
      <%= f.text_field :patient, :value=>@patient.name, :class=>'form-control', :disabled => true, :id=>'patient' %>
      <%= hidden_field_tag :patient_first_name, @patient.first_name %>
      <%= hidden_field_tag :patient_last_name, @patient.last_name %>
      <%= hidden_field_tag :patient_phone_number, @patient.phone_number %>
      <%= hidden_field_tag :patient_email, @patient.email %>
      <%= hidden_field_tag :patient_gender, @patient.gender %>
    </div>
    <div class='form-group'>
      <%= f.label :date_of_birth, "Date of Birth" %>
      <%= text_field_tag :date_of_birth, @patient.date_of_birth, :class=>'form-control', :disabled => true, :id=>'date_of_birth' %>
    </div>
    <div class='form-group'>
      <%= f.label :state, "Lives in State"%><br/>
      <%= f.subregion_select :state, 'US', {:priority => [@patient.state]}, :class=>'form-control', :value=>"#{@patient.state}"%>
      <%= hidden_field_tag :patient_street_1, @patient.street_1 %>
      <%= hidden_field_tag :patient_street_2, @patient.street_2 %>
      <%= hidden_field_tag :patient_city, @patient.city %>
      <%= hidden_field_tag :patient_zip, @patient.zip %>
    </div>

  </fieldset>

  <fieldset>
    <legend><h2>Prescription Details</h2></legend>

    <%= hidden_field :pharmacy_name, @prescription.pharmacy.name %>
    <%= hidden_field :pharmacy_street, @prescription.pharmacy.street %>
    <%= hidden_field :pharmacy_city, @prescription.pharmacy.city %>
    <%= hidden_field :pharmacy_state, @prescription.pharmacy.state %>
    <%= hidden_field :pharmacy_zip, @prescription.pharmacy.zip %>
    <%= hidden_field :pharmacy_fax, @prescription.pharmacy.fax %>
    <%= hidden_field :pharmacy_phone, @prescription.pharmacy.phone %>

    <div class="form-group">
      <%= f.label :drug_name, "Medication" %><br>
      <%= text_field_tag :prescription_drug_name, @prescription.drug_name, :class=>'form-control', :disabled => true %>
      <%= hidden_field_tag :drug_number, @prescription.drug_number, :class=>'form-control' %>
    </div>

    <div class='form-group'>
      <%= f.label :prescription_refills, "Refills" %>
      <%= text_field_tag :prescription_refills, @prescription.refills, :class=>'form-control', :disabled=>true %>
    </div>
    <div class='form-group'>
      <%= f.label :prescription_frequency, "Frequency" %>
      <%= text_field_tag :prescription_frequency, @prescription.frequency, :class=>'form-control', :disabled=>true %>
    </div>
    <div class='checkbox'>
      <%= f.label :prescription_dispense_as_written do %>
        <%= check_box_tag :prescription_dispense_as_written, @prescription.dispense_as_written, :class=>'checkbox', :disabled=>true %>
        <b>Dispense as Written?</b>
      <% end %>
    </div>
    <div class='form-group'>
      <%= f.label :prescription_quantity, "Quantity" %>
      <%= text_field_tag :prescription_quantity, @prescription.quantity, :class=>'form-control', :disabled=>true %>
    </div>

    <div class='checkbox'>
      <%= f.label :urgent do %>
      <%= f.check_box :urgent, :class=>'checkbox' %>
      <b>Urgent?</b>
      <% end %>
    </div>
    
    <div class='form-group'>
      <%= f.label :form_id, "Form" %>
      <%= f.text_field :form_id, :class=>'form-control' %>
    </div>

  </fieldset>
  <div class='form-actions'>
    <%= link_to "Cancel", @patient, :class=>'btn btn-default'%>
    <%= f.submit "Create", :class=>'btn btn-primary', :id=>'create'%>
  </div>
</div>

<% end %>

app/views/pa_requests/edit.html.erb
<h1>Editing Prior Authorization</h1>

<script lang='javascript'>
rp = new RequestPages({patientId: <%= patient_id %>, prescriptionId: <%= prescription_id %>, paRequestId: <%= id %>});
rp.showForm();
</script>

app/views/pa_requests/index.html.erb
<h2>Your Prior Auth Dashboard</h2>
<div id="dashboard"></div>

app/views/pa_requests/new.html.erb
<%= render 'form' %>

app/views/pa_requests/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Prescription</h2>
<p>
  <strong>Drug number:</strong>
  <%= @prescription.drug_number %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @prescription.quantity %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @prescription.frequency %>
</p>

<p>
  <strong>Refills:</strong>
  <%= @prescription.refills %>
</p>

<p>
  <strong>Dispense as written:</strong>
  <%= @prescription.dispense_as_written %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @prescription.patient %>
</p>

<h2>Request</h2>
<p>
  <strong>Form Id</strong>
  <%= @pa_request.form_id %>
</p>

<p><strong>Sent?</strong>
<%= @pa_request.sent %>
</p>

<p>
  <strong>Urgent?</strong>
  <%= @pa_request.urgent %>
</p>

<p>
  <strong>State</strong>
  <%= @pa_request.state %>
</p>

<%= link_to 'View Details', cmm_request_link_for(@pa_request), :class=>'btn btn-success' %>
<%= link_to 'Back', patient_path(@patient) %>