config/routes.rb
Rails.application.routes.draw do

  resources :patients do
    resources :prescriptions do
      resources :pa_requests do
        resource :request_pages
      end
    end
  end

  resources :pa_requests, :only => [:index]
  resource :request_pages, :only => [:show, :create]

  root 'home#index'

  get '/dashboard' => 'pa_requests#index'

  get '/help' => 'home#help'

  get '/api' => redirect("https://api.covermymeds.com/#overview"), :as => :api_documentation

end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  belongs_to :patient
  belongs_to :pharmacy, inverse_of: :prescriptions
  has_many :pa_requests

  validates :drug_number, :format=> {:with => /[0-9]+/ , :message => 'Drug Number is invalid'}
  scope :active, -> { where(active: true) }
  
  FREQUENCIES = [
    ['qD - EVERY DAY', 'qD'],
    ['BID - TWICE A DAY', 'BID'],
    ['TID - THREE A DAY', 'TID'],
    ['QID - FOUR A DAY', 'QID'],
    ['PRN - AS NEEDED', 'PRN'],
    ['UD - AS DIRECTED', 'UD']
  ]

end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: [:show, :edit, :update, :destroy]

  FORMULARY_STATUSES = ["Off formulary", "Tier 3/PA", "Tier 1", "Tier 2/PA"].freeze

  # GET /prescriptions
  # GET /prescriptions.json
  def index
    @patient = Patient.find(params[:patient_id])
    @prescriptions = Prescription.where(:patient_id => params[:patient_id]).where(:active => true)
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.json
  def show
  end

  # GET /patient/:patient_id/prescriptions/new
  def new
    @patient = Patient.find(params[:patient_id])
    @prescription = @patient.prescriptions.build
  end

  # GET /patient/:patient_id/prescriptions/1/edit
  def edit
  end

  # POST /patient/:patient_id/prescriptions
  # POST /patient/:patient_id/prescriptions.json
  def create
    @patient = Patient.find(params[:patient_id])
    @prescription = @patient.prescriptions.build(prescription_params)
    @prescription.formulary_status = FORMULARY_STATUSES.sample
    @prescription.date_prescribed = Time.zone.now
    @prescription.active = true

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @patient, notice: 'Prescription was successfully created.' }
        format.json { render :show, status: :created, location: @prescription }
      else
        format.html { render :new }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patient/:patient_id/prescriptions/1
  # PATCH/PUT /patient/:patient_id/prescriptions/1.json
  def update
    respond_to do |format|
      if @prescription.update(prescription_params)
        format.html { redirect_to @patient, notice: 'Prescription was successfully updated.' }
        format.json { render :show, status: :ok, location: @prescription }
      else
        format.html { render :edit }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient/:patient_id/prescriptions/1
  # DELETE /patient/:patient_id/prescriptions/1.json
  def destroy
    #@prescription.destroy
    # we never delete prescriptions.  they just get archived
    @prescription.active = false
    @prescription.save
    respond_to do |format|
      format.html { redirect_to @patient, notice: 'Prescription was archived.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescription
      @patient = Patient.find(params[:patient_id])
      @prescription = Prescription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prescription_params
      params.require(:prescription).permit(:drug_number, :quantity, :frequency, :refills, :dispense_as_written, :patient_id, :drug_name, :formulary_status, :pharmacy_id)
    end
  end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_form.html.erb
<%= form_for [@patient, @prescription], :class=>'form-vertical', :role=>'form' do |f| %>

<% if @prescription.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>

  <ul>
    <% @prescription.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div id="request-add" class="template">

  <fieldset>
    <legend>Prescription - <%= "#{@patient.first_name} #{@patient.last_name} (#{@patient.date_of_birth})" %></legend>

    <div class="form-group">
      <%= f.label :drug_number, "Medication" %><br>
      <%= f.text_field :drug_number, :class=>'form-control' %>
    </div>

    <div class="form-group">
      <%= f.hidden_field :drug_name, :class=>'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :quantity %><br>
      <%= f.number_field :quantity, :class=>'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :frequency , "Directions"%><br>
      <%= f.select :frequency, Prescription::FREQUENCIES, :class=>'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :refills, "Refills" %><br>
      <%= f.number_field :refills, :class=>'form-control', :in=>0..6 %>
    </div>


    <div class='checkbox'>
      <%= f.label :dispense_as_written do %>
      <%= f.check_box :dispense_as_written, :class=>'checkbox' %>
      <b>Dispense as Written?</b>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :pharmacy, "Filled By" %><br>
      <%= f.collection_select :pharmacy_id, Pharmacy.all, :id, :display_name %> 
    </div>

    <div class="actions">
      <% if @patient.prescriptions.empty? %>
      <%= link_to "Cancel", patients_path, :class=>'btn btn-default' %>
      <% else %>
      <%= link_to "Cancel", @patient, :class=>'btn btn-default' %>
      <% end %>
      <%= f.submit "Save", :class => 'btn btn-primary create', :onsubmit => 'getDrugName' %>
    </div>

  </fieldset>
</div>
<% end %>

app/views/prescriptions/edit.html.erb
<%= render 'form' %>

app/views/prescriptions/index.html.erb
<h1>Prescriptions for <%= "#{@patient.name} (#{@patient.date_of_birth})" %></h1>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Drug number</th>
      <th>Quantity</th>
      <th>Frequency</th>
      <th>Refills</th>
      <th>Dispense as written</th>
      <th>Patient</th>
    </tr>
  </thead>

  <tbody>
    <% @prescriptions.each do |prescription| %>
    <tr>
      <td><%= link_to prescription.drug_name, [@patient, prescription] %></td>
      <td><%= prescription.quantity %></td>
      <td><%= prescription.frequency %></td>
      <td><%= prescription.refills %></td>
      <td><%= prescription.dispense_as_written %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/prescriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Drug number:</strong>
  <%= @prescription.drug_number %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @prescription.quantity %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @prescription.frequency %>
</p>

<p>
  <strong>Refills:</strong>
  <%= @prescription.refills %>
</p>

<p>
  <strong>Dispense as written:</strong>
  <%= @prescription.dispense_as_written %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @prescription.patient %>
</p>

<%= link_to 'Edit', edit_patient_prescription_path(@patient, @prescription) %> |
<%= link_to 'Back', patient_prescriptions_path(@patient) %>