config/routes.rb
Rails.application.routes.draw do

  resources :patients do
    resources :prescriptions do
      resources :pa_requests do
        resource :request_pages
      end
    end
  end

  resources :pa_requests, :only => [:index]
  resource :request_pages, :only => [:show, :create]

  root 'home#index'

  get '/dashboard' => 'pa_requests#index'

  get '/help' => 'home#help'

  get '/api' => redirect("https://api.covermymeds.com/#overview"), :as => :api_documentation

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :prescriptions
  validates_presence_of :first_name, :last_name, :state
  validates :date_of_birth, :presence => true, :format => {with: /[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4}/, message: "must be DD/MM/YYYY"}

  def name
    "#{first_name} #{last_name}"
  end

  def requests
    num_requests = 0
    prescriptions.each do |p|
      num_requests += p.pa_requests.count
    end
    num_requests
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    if @patient.prescriptions.count == 0
      respond_to do |format|
        format.html {redirect_to new_patient_prescription_path(@patient)}
        format.json { render :show, status: :ok, location: @patient }
      end
    end
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patients_url, notice: "Patient created successfully." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patients_url, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
      @prescriptions = @patient.prescriptions.active
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :date_of_birth, :street_1, :street_2, :city, :state, :zip, :phone_number, :email, :gender)
    end
  end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
<% if @patient.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

  <ul>
    <% @patient.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div id="patient-add" class="template">
  <fieldset>
    <legend>Patient</legend>

    <div class='form-group'>
      <%= f.label :first_name, "First Name" %><br>
      <%= f.text_field :first_name, :class=>'form-control', :placeholder=>'First Name' %>
    </div>

    <div class='form-group'>
      <%= f.label :last_name, "Last Name" %><br>
      <%= f.text_field :last_name, :class=>'form-control', :placeholder=>'Last Name' %>
    </div>

    <div class='form-group'>
      <%= f.label :gender, "Gender" %>
      <%= f.select :gender, [['male', 'm'], ['female', 'f']] %>
    </div>

    <div class='form-group'>
      <%= f.label :date_of_birth, "Birthdate" %><br>
      <%= f.text_field :date_of_birth, :class=>'form-control datepicker', :placeholder=>"e.g. 01/01/1900" %>
    </div>

    <div class='form-group'>
      <%= f.label :street_1, "Street Address" %><br>
      <%= f.text_field :street_1, :class=>'form-control', :placeholder=>'1234 Main St.' %>
    </div>
    <div class='form-group'>
      <%= f.label :street_2, "Apartment/Suite #" %><br>
      <%= f.text_field :street_2, :class=>'form-control', :placeholder=>'Apartment/Suite #' %>
    </div>
    <div class='form-group'>
      <%= f.label :city, "City" %><br>
      <%= f.text_field :city, :class=>'form-control', :placeholder=>'City' %>
    </div>
    <div class='field'>
      <%= f.label :state, "State"%><br/>
      <%= f.subregion_select :state, 'US', {:priority => [@patient.state]}, :class=>'form-control', :value=>"#{@patient.state}"%>
    </div>

    <div class='form-group'>
      <%= f.label :zip, "Zip" %><br>
      <%= f.text_field :zip, :class=>'form-control', :placeholder=>'12345' %>
    </div>

    <div class='form-group'>
      <%= f.label :phone_number, "Phone Number" %><br>
      <%= f.text_field :phone_number, :class=>'form-control', :placeholder=>'e.g. 555-555-5555' %>
    </div>

    <div class='form-group'>
      <%= f.label :email, "Email" %><br>
      <%= f.text_field :email, :class=>'form-control', :placeholder=>'e.g. example@example.com' %>
    </div>

    <div class="actions">
      <%= link_to "Cancel", patients_path, :class=>"btn btn-default cancel" %>
      <%= f.submit "Create", :class => "btn btn-primary create" %>
    </div>

  </fieldset>
</div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

app/views/patients/index.html.erb
<div id="patients-list" class="template">
  <h1>Patients
    <%= link_to "Add patient", new_patient_path, :class=>'btn btn-small btn-success' %>
  </h1>

  <% if @patients.count < 1 %>
  <h2>No Patients</h2>
  <% end %>

  <table class="table table-striped">
    <tr class="header">
      <th class="open">Open PAs</th>
      <th>Patient Name</th>
      <th class="remove">Remove</th>
    </tr>
    <% @patients.each do |patient| %>
    <tr class="patients">
      <td class="open">
        <span class="label label-info"><%= patient.requests %></span>
      </td>
      <td>
        <%= link_to "#{patient.first_name} #{patient.last_name} (#{patient.date_of_birth})", patient %>
      </td>
      <td class="remove">
        <%= link_to "X", patient, method: :delete, :class=>'btn btn-xs btn-danger' %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/patients/new.html.erb
<%= render 'form' %>

app/views/patients/show.html.erb
<div id="patient-show" class="template">
  <h2><%= "#{@patient.last_name}, #{@patient.first_name} (#{@patient.date_of_birth}) - #{@patient.state} (#{@patient.email})" %><%= link_to 'Edit Patient', edit_patient_path(@patient), :class=>"btn btn-primary" %></h2>
  <hr>
  <h3>Prescriptions <%= link_to "Add Prescription", new_patient_prescription_path(@patient), :class=>'btn btn-success' %></h3>

  <% if @prescriptions.count < 1 %>
  <h5>No prescriptions have been added for this patient yet.</h5>
  <%  else  %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Medication</th>
        <th>Formulary Status</th>
        <th colspan="2">PA Status</th>
        <th colspan="2">Prescribed On</th>
      </tr>
    </thead>
    <% @prescriptions.each do |prescription| %>
    <tr>
      <% request = (prescription.pa_requests.first) || PaRequest.new %>
      <td><%= link_to prescription.drug_name, edit_patient_prescription_path(@patient, prescription), :class=>"btn btn-primary #{(request.sent) ? 'disabled' : ''}" %></td>
      <td><%= prescription.formulary_status %></td>

      <td><%= request.cmm_workflow_status || "Not yet started" %></td>

      <td class="start">
        <% if (request == nil) || (request.cmm_token == nil) then %>
        <%= link_to "Start", new_patient_prescription_pa_request_path(@patient, prescription), :class=>'btn btn-success', :id => 'start_pa_request' %>
        <%  else  %>
        <%= link_to "Edit PA", patient_prescription_pa_request_path(@patient, prescription, request), :class=>'btn btn-success', :id => 'edit_pa_request' %>
        <% end %>
      </td>
      <td><%= prescription.date_prescribed && prescription.date_prescribed.strftime("%B %d at %I:%M %p") %></td>
      <td>
            <%= link_to "X", [@patient, prescription], method: :delete, :class=>'btn btn-xs btn-danger' %>
      </td>
    </tr>
    <% end %>
  </table>
  <% end %>

  

</div>