config/routes.rb
Rails.application.routes.draw do

  resources :patients do
    resources :prescriptions do
      resources :pa_requests do
        resource :request_pages
      end
    end
  end

  resources :pa_requests, :only => [:index]
  resource :request_pages, :only => [:show, :create]

  root 'home#index'

  get '/dashboard' => 'pa_requests#index'

  get '/help' => 'home#help'

  get '/api' => redirect("https://api.covermymeds.com/#overview"), :as => :api_documentation

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :request_tokens

  def request_tokens
    PaRequest.select('cmm_token').inject([]) {|acc,n| acc.push("'#{n.cmm_token}'")}
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(key)
    case key
    when :notice then
      'alert alert-info'
    when :success then
      'alert alert-success'
    when :error then
      'alert alert-danger'
    when :alert then
      'alert alert-danger'
    end
  end

  def ehr_error_messages(flash)
    html = "<div class='row'>"
    flash.each do |key, value| 
      html += <<-HTML
      <div class="alert alert-info fade in" id="flash_#{value}">
        <button type='button' class='close' data-dismiss='alert'>&times;</button>
        #{value}
      </div>      
      HTML
    end

    html.html_safe
  end
  
end

app/views/application/_application_navbar.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "M 'r' Us", root_path, :class=>'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "Patients", patients_path %>
        </li>
        <li><%= link_to "Prior Authorizations", pa_requests_path %></li>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
          <li class='dropdown'>
            <a href='#' class='dropdown-toggle' data-toggle='dropdown'>Resources<b class='caret'></b></a>
            <ul class='dropdown-menu'>
              <li><%= link_to "Contact CoverMyMeds", help_path %></li>
              <li><%= link_to "API Documentation", api_documentation_path %></li>
            </ul>
          </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>